apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: {{ name }}
spec:
  size: {{ nodes }}
  flux:
    topology: {{ topo }}
    container:
      disable: true
  logging:
    quiet: true
  containers:
    - image: ghcr.io/converged-computing/container-chonks:topology-flux-0.66.0
      command: /bin/bash /entrypoint.sh
      launcher: true
      # pullAlways: true
      commands:
        pre: |
          python3 -m pip install Jinja2 
          python3 /topology_experiment.py --leaf-nodes {{ leaf_nodes }} --middle-nodes {{ middle_nodes }} --max-size {{ max_size }} --nodes {{ nodes }} --topo {{ topo }}
