apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: {{ name }}
spec:
  size: {{ nodes }}
  flux:
    topology: {{ topo }}
    container:
      disable: true
  containers:
    - image: ghcr.io/converged-computing/topology-experiment:test
      launcher: true
      pullAlways: true
      # The topology_experiment.py below writes this file
      command: /bin/bash /entrypoint.sh
      # pullAlways: true
      commands:
        pre: python3 /topology_experiment_quick.py --nodes {{ nodes }} --topo {{ topo }}
